name: Release vllm-proxy

on:
  push:
    tags:
      - 'v*'

permissions:
  attestations: write
  id-token: write
  contents: write
  packages: write

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vllm-proxy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clean up Docker resources
        run: |
          docker system df
          docker system prune -a -f
        working-directory: .

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/vllm-proxy:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: "docker.io/${{ vars.DOCKERHUB_USERNAME }}/vllm-proxy"
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Docker Image Digest (SHA256)

            | Image | Digest | Verification |
            |---|---|---|
            | `docker.io/${{ vars.DOCKERHUB_USERNAME }}/vllm-proxy:${{ github.ref_name }}` | `${{ steps.build-and-push.outputs.digest }}` | [Verify on Sigstore](https://search.sigstore.dev/?search=${{ steps.build-and-push.outputs.digest }})